# Generated by Django 3.2.4 on 2021-06-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
    ]
