# Generated by Django 3.2.4 on 2021-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_explain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explain',
        ),
        migrations.AddField(
            model_name='blog',
            name='explain',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
